version: 0.2
phases:
  install:
    commands:
      - curl -fsSL https://releases.hashicorp.com/terraform/1.9.8/terraform_1.9.8_linux_amd64.zip -o /tmp/terraform.zip
      - unzip -o /tmp/terraform.zip -d /usr/local/bin/
      - terraform --version
  build:
    commands:
      - cd application
      - terraform fmt -check -recursive
      - terraform init -backend=false
      - terraform validate
