version: 0.2
phases:
  install:
    commands:
      - yum install -y yum-utils
      - yum-config-manager --add-repo https://rpm.releases.hashicorp.com/AmazonLinux/hashicorp.repo
      - yum install -y terraform
  build:
    commands:
      - cd application
      - terraform fmt -check -recursive
      - terraform init -backend=false
      - terraform validate
